### ISSUE TITLE
Script gets triggered twice..?

### ISSUE THREAD

**Issue by heisian** [Raudius/files_scripts#154] opened 2024-01-19 02:38 UTC
I have a simple script that sends a Slack notification when a particular file is created. It works, but the script seems to get triggered twice.

Here is my flow configuration:
![image](https://github.com/Raudius/files_scripts/assets/4141828/bd6838b9-5dc7-4a26-a60a-5c9d81f0a938)

Here is my LUA script:
``` lua
-- Get user that accessed file
local user = users_find(nil)[1]

-- Get name of file being accessed
local file = get_input_files()[1]

-- Create JSON payload for Slack webhook
local payload = "{\"text\":\"" .. user["display_name"] .. " has opened " .. file_name .. "\"}"

-- Send Slack notification
http_request("https://hooks.slack.com/services/<WEBHOOK_URL>", "POST", payload)
```

Finally, here is the resulting double notification in Slack that occurs because the script gets triggered twice:
![image](https://github.com/Raudius/files_scripts/assets/4141828/6467b8ae-6a05-4740-ad73-a4588cfb85ce)

I'm not sure how to debug this issue.. I've tried uninstalling and reinstalling this app to no avail. Help please!

**Comment by Raudius** [comment] 2024-01-19 11:37
I tested your flow with `*.odt` files, and could not reproduce it. So I'm inclined to say its likely the CAD viewer app that is triggering two "file access" events when opening the file.

Another thing I noticed is that the flow only got triggered on file-creation, so I am also not sure what the workflow engine qualifies as a file access.

**Comment by Raudius** [comment] 2024-02-04 16:12
Closing for now, feel free to reopen with more details :)

**Closed by Raudius** 2024-02-04 16:12 UTC
