### ISSUE TITLE
Not working after NC 28 + 4.0.0 upgrade

### ISSUE THREAD

**Issue by tuxArg** [Raudius/files_scripts#143] opened 2023-12-26 23:43 UTC
Hi, I've recently upgraded to Nextcloud 28 (from version 27) and yesterday I upgraded files_scripts to 4.0.0.

I don't remember if it was working after the upgrade from 27 to 28, but I think it was.

I don't see any errors on server side, just on the client browser. If I open "More actions" submenu a '"More actions" action failed' error appears. In the js console I can see:

ConsoleLogger.js:74 [ERROR] files: Error while executing action {app: 'files', uid: 'myuser', level: 2, action: {…}, e: TypeError: Cannot read properties of undefined (reading 'some')
    at o.onActionClick (https://myc…}action: {id: 'files_scripts_action', displayName: ƒ, title: ƒ, iconSvgInline: ƒ, enabled: ƒ, …}displayName: (e,t)=>nenabled: (e,n)=>null===t||(0,h.$P)(t,e)exec: ƒ exec(t,n,r)execBatch: ƒ execBatch(t,n,r)iconSvgInline: (e,t)=>fid: "files_scripts_action"order: 1001title: (e,t)=>n[[Prototype]]: Objectapp: "files"e: TypeError: Cannot read properties of undefined (reading 'some')
    at o.onActionClick (https://mycloud.tld/dist/files-main.js?v=2909d0ce-10:2:87296)level: 2uid: "myuser"[[Prototype]]: Object

If you need any other info please let me know. Thanks!

**Comment by Raudius** [comment] 2023-12-27 05:55
I could not reproduce on a fresh install of `Nextcloud 28` + `files_scripts`.

Could you first try opening it in a private window to check that its not a case of old javascript being cached in the browser.

If that doesnt work could you check in the dev tools `Network` tab if there is a failed request to the `/index.php/apps/files_scripts/scripts` endpoint when you open the files app.

**Comment by tuxArg** [comment] 2023-12-27 12:23
Hi @Raudius ,

I can see HTTP 200 requests to https://mycloud.tld/apps/files_scripts/scripts (pretty urls enabled). Here's an example response:
[
    {
        "id": 5,
        "title": "My function",
        "description": "",
        "program": "",
        "enabled": 1,
        "showInContext": 0,
        "limitGroups": [],
        "public": 0,
        "fileTypes": []
    }
 ]

There are successful requests too to:
/apps/files_scripts/css/globals.css
/apps/files_scripts/css/icons.css
/apps/files_scripts/js/files_scripts-main.js

There's another console error I found, probably related:
vue.runtime.esm.js (line 3049):
TypeError: Cannot read properties of undefined (reading 'split')
    at script.ts:54:41
    at Array.every (<anonymous>)
    at s (script.ts:50:18)
    at ScriptSelect.vue:39:48
    at Array.filter (<anonymous>)
    at o.scripts (ScriptSelect.vue:39:36)
    at e.get (vue.runtime.esm.js:3446:33)
    at e.evaluate (vue.runtime.esm.js:3547:27)
    at o.scripts (vue.runtime.esm.js:5541:25)
    at o.<anonymous> (ScriptSelect.vue:1:365)

**Comment by tuxArg** [comment] 2023-12-27 12:36
Just more info. If I check the "experimental interpreter" option, same error appears, but the more actions menu opens anyway and the functions don't work ("Action failed unexpectedly").

**Comment by Raudius** [comment] 2023-12-27 12:52
What browser are you using?

Did you also try using an incognito window or clearing the browser cache?

**Comment by tuxArg** [comment] 2023-12-27 13:06
Hi @Raudius ,

It's chromium. Yes, I cleared cache, also tried incognito, firefox and Android chrome. All the same.

**Comment by Raudius** [comment] 2023-12-27 13:11
Could you give me more information about the script(s) you  have enabled? What options do you have selected (file types, groups) also what sort of inputs do you have?

**Comment by tuxArg** [comment] 2023-12-27 13:20
Sure, here's a rotate/mirror image function I wrote. There are 4 checkboxs. By the way, example functions don't work either. The error is when I open the "more actions" menu.
[rotate.lua.txt](https://github.com/Raudius/files_scripts/files/13778805/rotate.lua.txt)

**Comment by Raudius** [comment] 2023-12-27 17:12
Turned out the issue was related to scripts with file type restrictions. 

Let me know if `4.0.1` fixes it for you

**Comment by tuxArg** [comment] 2023-12-27 22:50
Hi @Raudius 
It's not working. I've been trying with no success.
The "more actions" menu shows the same error.
If I check the "show in context menu" then that function is shown. If I click it, then inmediately an _"myFunctionName" action failed_ error is shown. All options and checkboxes are displayed but if I run the action I get a 404 error in the POST request to /apps/files_scripts/run/5 (previous GET request does work).
Maybe my app installation is messed. What's the correct way to clean all this app related in the db so I can try a fresh app install ? (i've tried uninstalling and reinstalling but all my scripts are there, removing them all and importing a new function didn't work. maybe something is wrong and keeps being that way)

Thanks

**Comment by Raudius** [comment] 2023-12-28 06:20
Can you verify that removing whether removing file type restrictions from all enabled scripts "solves" the issue? Could you try again clearing cache or using a private window after the `4.0.1` update?

Unfortunately there is no easy way to "clean" apps in Nextcloud. Specially if you start removing tables, then rerunning the migrations is not straightforward as the server thinks they already ran.

Also in this case the issue is specifically in the frontend so resetting the app backend shouldnt do anything.

**Comment by tuxArg** [comment] 2023-12-28 13:29
Hi @Raudius ,
I tried that. Same errors.
```
user@nextcloud:~$ occ files_scripts:list
Listing file actions:
id	name
15	Test
user@nextcloud:~$ occ files_scripts:export -i 15 
{"id":15,"title":"Test","description":"","program":"add_message(\"This is a test!\")","enabled":1,"showInContext":0,"limitGroups":[],"public":0,"fileTypes":[],"inputs":[]}
```
Do you know if it's possible to downgrade to 3.x version? Just to see if that solves it?

**Comment by Raudius** [comment] 2023-12-28 13:48
I'm a bit out of ideas, can you try running:

```
occ migrations:status files_scripts
```

> Do you know if it's possible to downgrade to 3.x version? Just to see if that solves it?

This wont work, because Nextcloud 28 changed the Files app, so the integration is completely broken in `3.x.x`.

**Comment by tuxArg** [comment] 2023-12-28 16:16
```
user@nextcloud:~$ occ migrations:status files_scripts


  There are no commands defined in the "migrations" namespace.
```
Are you sure is that command?

**Comment by tuxArg** [comment] 2023-12-28 16:21
Got it!
```
user@nextcloud:~$ occ migrations:status files_scripts
    >> App:                                                files_scripts
    >> Version Table Name:                                 oc_migrations
    >> Migrations Namespace:                               OCA\FilesScripts\Migration
    >> Migrations Directory:                               /var/www/nextcloud/apps/files_scripts/lib/Migration
    >> Previous Version:                                   031000Date20231211
    >> Current Version:                                    040000Date20231217
    >> Next Version:                                       Already at latest migration step
    >> Latest Version:                                     040000Date20231217
    >> Executed Migrations:                                10
    >> Executed Unavailable Migrations:                    10
    >> Available Migrations:                               10
    >> New Migrations:                                     10
    >> Pending Migrations:                                 None
```

**Comment by Raudius** [comment] 2023-12-28 18:03
All looks good with the migrations as well, so I really don't know what could be going wrong.

Can you try a different browser?

Does it happen to all users?

**Comment by tuxArg** [comment] 2023-12-28 20:00
> All looks good with the migrations as well, so I really don't know what could be going wrong.
> 
> Can you try a different browser?
I've tried android chrome and ubuntu firefox and chromium
> 
> Does it happen to all users?
Yes, it does.

Can you guide me how to run a function with `occ files_scripts:run`? Maybe if that doesn't work either then it's not a browser or client issue.

**Comment by Raudius** [comment] 2023-12-30 07:52
```
$ occ files_scripts:list
Listing file actions:
id	name
5	Hello world
```

```
$ occ files_scripts:export -i 5
{"id":5,"title":"Hello world","description":"","program":"print(\"hello world\")","enabled":0,"showInContext":0,"limitGroups":[],"public":0,"fileTypes":[],"inputs":[]}
```

```
$ occ files_scripts:run -u admin 5
Executing file action: Hello world
hello world
File action executed successfully.
```

**Comment by tuxArg** [comment] 2023-12-30 11:38
Hi @Raudius ,

I think I made some progress here. Scripts (even complex scripts) are only working on root directory. Even your example doesn't work if I'm in any subdir.

**Comment by Raudius** [comment] 2023-12-30 12:40
Wow, thanks for that insight, I did not think to test files inside a folder. 

I found the bug and merged a fix with https://github.com/Raudius/files_scripts/pull/146 that should hopefully solve this issue. Will now proceed with the `4.0.2` release.

Let me know if the issue persists after updating.

**Closed by Raudius** 2023-12-30 12:40 UTC
Labels: bug

**Comment by tuxArg** [comment] 2023-12-30 14:40
#146 worked!

There's still an only visual but misleading error message immediately after menu option is clicked:
- "function name" action failed     (when context menu is enabled)
- or, "More actions" action failed

But menu or action window open anyway and work fine.
This happens in root directory too, so probably not related.

**Comment by Raudius** [comment] 2023-12-30 14:52
Great to hear!

> There's still an only visual but misleading error message immediately after menu option is clicked:

Where does this error show up in a toast message or in the browser console?

Once again I cannot reproduce the same behaviour :/

**Comment by tuxArg** [comment] 2023-12-30 15:24
> > There's still an only visual but misleading error message immediately a
> Where does this error show up in a toast message or in the browser console?

It's a nextcloud style toast message with red line left border (indicating a warning or error)

**Comment by tuxArg** [comment] 2023-12-30 17:42
Hi @Raudius ,

I'm not an expert here and I don't know how to test it either. But I've been reading your code and I think the issue could be the `exec` and `execBatch` you send to `registerFileAction`. Those should be `<boolean|null>` and not `<void>`. Maybe I'm wrong. Again, I don't know how to test it.

**Comment by Raudius** [comment] 2023-12-30 19:25
Yes! I was actually able to reproduce it and the execution promise was definitely the issue.

I have fixed it in https://github.com/Raudius/files_scripts/pull/149 but I will wait on the release a few days and do it in the new year.

Thanks a lot for the help

**Comment by tuxArg** [comment] 2024-01-01 12:33
Thank you! I'll wait the next release then
